#!/usr/bin/env python3
"""
Bug Filer Utility
Inspired by Apple's internal Radar bug filing system.
Automatically gathers system information and guides the reporter
through structured bug documentation.
Author: Deandre Medrano
"""

import platform
import datetime
import subprocess
import sys
import os


def get_system_info():
    """Auto-detect system environment information."""
    info = {}

    # OS Information
    info["os"] = platform.system()
    info["os_version"] = platform.version()
    info["os_release"] = platform.release()
    info["machine"] = platform.machine()
    info["processor"] = platform.processor()

    # macOS specific
    if platform.system() == "Darwin":
        try:
            mac_ver = platform.mac_ver()[0]
            info["macos_version"] = f"macOS {mac_ver}"
        except:
            info["macos_version"] = "Unknown"

    # Python version
    info["python_version"] = sys.version.split()[0]

    # Browser detection (Chrome)
    try:
        result = subprocess.run(
            ["/Applications/Google Chrome.app/Contents/MacOS/Google Chrome", "--version"],
            capture_output=True, text=True
        )
        info["browser"] = result.stdout.strip()
    except:
        info["browser"] = "Chrome not found or not on macOS"

    # Screen resolution (macOS)
    try:
        result = subprocess.run(
            ["system_profiler", "SPDisplaysDataType"],
            capture_output=True, text=True
        )
        for line in result.stdout.split("\n"):
            if "Resolution" in line:
                info["screen_resolution"] = line.strip()
                break
    except:
        info["screen_resolution"] = "Unknown"

    return info


def get_bug_id():
    """Generate a unique bug ID."""
    now = datetime.datetime.now()
    return f"BUG-{now.strftime('%Y%m%d%H%M%S')}"


def prompt(question, required=True):
    """Prompt user for input."""
    while True:
        answer = input(f"\n{question}\n> ").strip()
        if answer or not required:
            return answer
        print("This field is required. Please enter a value.")


def prompt_steps():
    """Interactively collect steps to reproduce."""
    print("\nSteps to Reproduce")
    print("Enter each step and press Enter. Type 'done' when finished.")
    steps = []
    step_num = 1
    while True:
        step = input(f"  Step {step_num}: ").strip()
        if step.lower() == "done":
            break
        if step:
            steps.append(step)
            step_num += 1
    return steps


def prompt_severity():
    """Prompt for severity level."""
    print("\nSeverity Level")
    print("  1. Critical — App crash, data loss, security vulnerability")
    print("  2. High     — Major feature broken, no workaround")
    print("  3. Medium   — Feature partially broken, workaround exists")
    print("  4. Low      — Minor issue, cosmetic, edge case")
    while True:
        choice = input("\n> ").strip()
        levels = {"1": "Critical", "2": "High", "3": "Medium", "4": "Low"}
        if choice in levels:
            return levels[choice]
        print("Please enter 1, 2, 3, or 4.")


def prompt_priority():
    """Prompt for priority level."""
    print("\nPriority Level")
    print("  P1 — Must fix before release")
    print("  P2 — Should fix before release")
    print("  P3 — Fix if time permits")
    print("  P4 — Nice to have")
    while True:
        choice = input("\n> ").strip().upper()
        if choice in ["P1", "P2", "P3", "P4"]:
            return choice
        print("Please enter P1, P2, P3, or P4.")


def generate_report(bug_id, system_info, bug_data):
    """Generate formatted bug report."""
    now = datetime.datetime.now().strftime("%B %d, %Y at %I:%M %p")

    steps_formatted = "\n".join(
        [f"  {i+1}. {step}" for i, step in enumerate(bug_data["steps"])]
    )

    report = f"""
================================================================================
BUG REPORT — {bug_id}
Generated by Bug Filer Utility | Inspired by Apple Radar
================================================================================

SUMMARY
-------
{bug_data['summary']}

METADATA
--------
Bug ID:     {bug_id}
Date:       {now}
Reporter:   {bug_data['reporter']}
Component:  {bug_data['component']}
Version:    {bug_data['version']}
Status:     Open
Severity:   {bug_data['severity']}
Priority:   {bug_data['priority']}

ENVIRONMENT (Auto-Detected)
----------------------------
OS:               {system_info.get('macos_version', system_info.get('os', 'Unknown'))} {system_info.get('os_release', '')}
Machine:          {system_info.get('machine', 'Unknown')}
Browser:          {system_info.get('browser', 'Unknown')}
Python:           {system_info.get('python_version', 'Unknown')}
Screen:           {system_info.get('screen_resolution', 'Unknown')}

STEPS TO REPRODUCE
------------------
{steps_formatted}

EXPECTED RESULT
---------------
{bug_data['expected']}

ACTUAL RESULT
-------------
{bug_data['actual']}

IMPACT
------
{bug_data['impact']}

POSSIBLE ROOT CAUSE
-------------------
{bug_data['root_cause']}

ADDITIONAL NOTES
----------------
{bug_data['notes'] or 'None'}

ATTACHMENTS NEEDED
------------------
[ ] Screenshot
[ ] Screen recording
[ ] Console logs
[ ] Network logs
[ ] Crash report

================================================================================
END OF REPORT — {bug_id}
================================================================================
"""
    return report


def save_report(bug_id, report):
    """Save report to file."""
    filename = f"{bug_id}.txt"
    with open(filename, "w") as f:
        f.write(report)
    return filename


def main():
    print("=" * 60)
    print("  Bug Filer Utility")
    print("  Inspired by Apple's Radar Bug Filing System")
    print("=" * 60)
    print("\nDetecting your system environment automatically...")

    # Auto-detect system info
    system_info = get_system_info()
    bug_id = get_bug_id()

    print(f"\n✓ OS:      {system_info.get('macos_version', system_info.get('os', 'Unknown'))}")
    print(f"✓ Browser: {system_info.get('browser', 'Unknown')}")
    print(f"✓ Python:  {system_info.get('python_version', 'Unknown')}")
    print(f"✓ Bug ID:  {bug_id}")

    print("\n" + "-" * 60)
    print("Let's file your bug. Answer each question carefully.")
    print("-" * 60)

    # Collect bug information
    bug_data = {}

    bug_data["reporter"] = prompt("Your name:")
    bug_data["summary"] = prompt("Bug summary (one clear sentence describing the issue):")
    bug_data["component"] = prompt("Component or feature area affected (e.g. Login, Checkout, API):")
    bug_data["version"] = prompt("App or software version (e.g. 2.1.0, build 1234):")
    bug_data["severity"] = prompt_severity()
    bug_data["priority"] = prompt_priority()
    bug_data["steps"] = prompt_steps()
    bug_data["expected"] = prompt("Expected Result (what should happen):")
    bug_data["actual"] = prompt("Actual Result (what actually happens):")
    bug_data["impact"] = prompt("Impact (who is affected and how severely):")
    bug_data["root_cause"] = prompt("Possible Root Cause (your best technical hypothesis):")
    bug_data["notes"] = prompt("Additional notes or context (press Enter to skip):", required=False)

    # Generate and save report
    print("\n" + "=" * 60)
    print("Generating bug report...")
    report = generate_report(bug_id, system_info, bug_data)
    filename = save_report(bug_id, report)

    print(report)
    print(f"\n✓ Report saved to: {filename}")
    print("✓ Ready to paste into Jira, Linear, or Apple Radar")


if __name__ == "__main__":
    main()